name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_1h68PNU6EjiEcUo2TX0a8E9A
          VERCEL_PROJECT_ID: prj_8hpO4WIc79FCubhPr8KPT3WlItVP
